### PR TITLE
initial scafold of project

### PR DESCRIPTION
**Pull request by jatanolu**

### CODE REVIEW

**Comment by nadiacollado** [comment]
Hi, is there a ticket associated with this PR? If so, can you change the title to include the ticket number and title? e.g. TODO-001 Display a list of tasks

The same would usually be applied to the branch name as well: todo-001-display-a-list-of-tasks

**Comment by nadiacollado** [comment]
Re: commits, use the following convention:

```
- Commits should be prepended by the ticket number 
ie: TODO-001 Display a single task, TODO-001 Display multiple tasks
- should be in the imperative mood (Fix a typo, and not Fixes a type, Fixing a typo, Fixed a typo)
- capitalize first word
```

**Comment by jatanolu** [comment]
No ticket is assigned to this PR. This was more of a sample PR to bring everyone to the repo. I will make sure to try and follow the proper convention for commits. Would I have to close this PR, change the commit and open it again or is there another process?

**Review by skp96 — APPROVED** [review]
Approving since this was part of the initial setup. @jatanolu is aware of the process for PRs in the future.

**Comment by nadiacollado** [comment]
> No ticket is assigned to this PR. This was more of a sample PR to bring everyone to the repo. I will make sure to try and follow the proper convention for commits. Would I have to close this PR, change the commit and open it again or is there another process?

You can simply go back, [change the commits, and force push up](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message). But we don't need to do all that for this. Thanks for clarifying!

**Review by nadiacollado — APPROVED** [review]

**Pull request merged**
